apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: cirkel-dev
  annotations:
    nginx.org/rewrites: "serviceName=auth rewrite=/"
    nginx.ingress.kubernetes.io/auth-url: http://auth.cirkel-dev.svc.cluster.local/validate
spec:
  ingressClassName: nginx
  tls:
    - secretName: pg-api-tls
      hosts:
      - cirkel-dev.api.pandudpn.id
  rules:
  - host: cirkel-dev.api.pandudpn.id
    http:
      paths:
      - backend:
          service:
            name: auth
            port:
              number: 80
        pathType: Prefix
        path: /auth/
