apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cirkel-backend
  namespace: cirkel-dev
  annotations:
    nginx.org/rewrites: "serviceName=auth rewrite=/"
spec:
  ingressClassName: nginx
  tls:
  - secretName: pg-tls
    hosts:
    - cirkel-api.pandudpn.id
  rules:
  - host: cirkel-api.pandudpn.id
    http:
      paths:
      - backend:
          service:
            name: auth
            port:
              number: 80
        pathType: Prefix
        path: /auth/
