name: Update Configuration

on:
  push:
    branches:
      - master

jobs:
  file_changes:
    name: List all File Changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Changes Files
        id: changes_files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"

  deploy:
    name: Deploy updated Configurations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          mv sops-v3.8.1.linux.amd64 /usr/local/bin/sops
          chmod +x /usr/local/bin/sops
          sops --version

      - name: Decrypt Configs
        run: |
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
          sops -d -i dev/config.json

      - name: Deploy to k8s Cluster
        uses: yokawasa/action-setup-kube-tools@v0.9.2
      - run: |
          kubectl config set-cluster ${{ secrets.CLUSTER_NAME }} --server="${{ secrets.CLUSTER_SERVER }}"
          kubectl config set-context ${{ secrets.CLUSTER_ALIAS }} --cluster=${{ secrets.CLUSTER_NAME }} --user=${{ secrets.CLUSTER_USER }}
          kubectl config set clusters.${{ secrets.CLUSTER_NAME }}.certificate-authority-data "${{ secrets.CLUSTER_CERFITICATE_AUTHORITY }}"
          kubectl config set users.${{ secrets.CLUSTER_USER }}.client-certificate-data "${{ secrets.CLUSTER_CLIENT_CERTIFICATE }}"
          kubectl config set users.${{ secrets.CLUSTER_USER }}.client-key-data "${{ secrets.CLUSTER_CLIENT_KEY }}"
          kubectl config use-context ${{ secrets.CLUSTER_ALIAS }}