name: Update Configuration

on:
  push:
    branches:
      - master

jobs:
  changes:
    name: List all File Changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Changes Files
        id: changes_files
        uses: tj-actions/changed-files@v35
    outputs:
      list_files: ${{ steps.changes_files.outputs.all_changed_files }}

  deploy:
    name: Deploy updated Configurations
    runs-on: ubuntu-latest
    needs:
      - changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          mv sops-v3.8.1.linux.amd64 /usr/local/bin/sops
          chmod +x /usr/local/bin/sops
          sops --version

      - name: Deploy to k8s Cluster
        uses: yokawasa/action-setup-kube-tools@v0.9.2
      - run: |
          echo ${{ secrets.KUBECONFIG }} > $HOME/.kube/config
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
          sops -d -i dev/shared/shared.json

          for dir in $(echo ${{ needs.changes.outputs.list_files }}); do
            if [ $(echo $dir | cut -d '/' -f1) == "dev" ]
            then
              serviceType=$(echo $dir | cut -d '/' -f2)
              if [ $serviceType == "service" ]
              then
                fileName=$(echo $dir | cut -d '/' -f3)
                serviceName=$(echo $fileName | cut -d '.' -f1)
                sops -d -i dev/service/$fileName
                kubectl exec -it -n etcd etcd-0 bash -- etcdctl put "$serviceName" "$(jq -c -s '.[0] * .[1]' dev/shared/shared.json dev/service/$fileName)"
              fi
            fi
          done
          